version: 0.2

env:
  variables:
    REPOSITORY_URI: "https://github.com/hkhan24/BasicMicroService.git"  # replace this with your ECR URI

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo "Building Docker image..."
      - docker build -t basicmicroservice .

  build:
    commands:
      - echo "Tagging Docker image..."
      - docker tag basicmicroservice:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - echo "Build completed!"
