version: 0.2

env:
  variables:
    REPOSITORY_URI: "https://github.com/hkhan24/BasicMicroService.git"  # replace this with your ECR URI

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Building Docker image..."
      - docker build -t basicmicroservice .

  build:
    commands:
      - echo "Tagging Docker image..."
      - docker tag basicmicroservice:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - echo "Build completed!"
