version: 0.2

env:
  variables:
    REPOSITORY_URI: "public.ecr.aws/a4c9g4h8/basicmicroservice"  # replace this with your ECR URI

phases:
  pre_build:
    commands:
      - echo "Building Docker image..."
      - docker build -t basicmicroservice .

  build:
    commands:
      - echo "Tagging Docker image..."
      - docker tag basicmicroservice:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - echo "Build completed!"
